# Generated by Django 6.0.1 on 2026-01-12 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('clave', models.CharField(blank=True, default='---', max_length=50, null=True)),
                ('domicilio', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('provincia', models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('Capital Federal', 'Capital Federal'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Córdoba', 'Córdoba'), ('Corrientes', 'Corrientes'), ('Entre Ríos', 'Entre Ríos'), ('Formosa', 'Formosa'), ('Jujuy', 'Jujuy'), ('La Pampa', 'La Pampa'), ('La Rioja', 'La Rioja'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquén', 'Neuquén'), ('Río Negro', 'Río Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Santiago del Estero', 'Santiago del Estero'), ('Tierra del Fuego', 'Tierra del Fuego'), ('Tucumán', 'Tucumán')], max_length=50)),
                ('codigo_postal', models.CharField(max_length=8)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('cuil_cuit', models.CharField(max_length=20)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('condicion_afip', models.CharField(blank=True, choices=[('IVA Responsable No Inscripto', 'IVA Responsable No Inscripto'), ('IVA Sujeto Exento', 'IVA Sujeto Exento'), ('Consumidor Final', 'Consumidor Final'), ('Responsable Monotributo', 'Responsable Monotributo'), ('Proveedor del Exterior', 'Proveedor del Exterior'), ('Cliente del Exterior', 'Cliente del Exterior'), ('IVA Liberado - Ley 19.640', 'IVA Liberado - Ley 19.640'), ('Monotributista Social', 'Monotributista Social'), ('IVA No Alcanzado', 'IVA No Alcanzado')], max_length=30, null=True)),
                ('razon_social', models.CharField(blank=True, default='---', max_length=128, null=True)),
                ('domicilio_comercial', models.CharField(blank=True, default='---', max_length=128, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
