# Generated by Django 6.0.1 on 2026-01-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_oferta',
            field=models.BooleanField(default=False, verbose_name='¿Es Oferta?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio de Oferta'),
        ),
    ]
