# Generated by Django 6.0.1 on 2026-01-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal_base', models.CharField(help_text='Código postal de la dirección base', max_length=10)),
                ('calle', models.CharField(max_length=255)),
                ('altura', models.CharField(max_length=10)),
                ('localidad', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('tarifa_por_km', models.DecimalField(decimal_places=2, help_text='Costo por kilómetro', max_digits=10)),
            ],
        ),
    ]
